/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'speedotrack';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ANTENNA = 'assets/antenna.png';
  static const String APPICON = 'assets/appsicon/appIcon.png';
  static const String BATTERY = 'assets/battery.png';
  static const String CAR = 'assets/car.png';
  static const String ELECTRICBATERY = 'assets/electricbatery.png';
  static const String POWER = 'assets/power.png';
  static const String SATTELITE = 'assets/sattelite.png';
  static const String SENSOR = 'assets/sensor.png';
  static const String SPEEDOMETER = 'assets/speedometer.png';

  // ==========================================
  // TRACCAR API BACKEND ASSET INTEGRATION
  // ==========================================

  /// Traccar Device custom image API URL (`/api/devices/{id}/image`)
  static String getTraccarDeviceImageUrl(String baseUrl, int deviceId) {
    final cleanBase = baseUrl.endsWith('/') ? baseUrl.substring(0, baseUrl.length - 1) : baseUrl;
    return '$cleanBase/api/devices/$deviceId/image';
  }

  /// Traccar Server hosted custom file/logo API URL (`/api/server/file/{path}`)
  static String getTraccarServerFileUrl(String baseUrl, String path) {
    final cleanBase = baseUrl.endsWith('/') ? baseUrl.substring(0, baseUrl.length - 1) : baseUrl;
    final cleanPath = path.startsWith('/') ? path.substring(1) : path;
    return '$cleanBase/api/server/file/$cleanPath';
  }

  /// Traccar Device Category String ko local Asset Path ke sath map karne ka helper
  static String getIconByTraccarCategory(String? category) {
    if (category == null || category.isEmpty) return CAR;

    switch (category.toLowerCase()) {
      case 'car':
      case 'auto':
      case 'vehicle':
      case 'truck':
      case 'bus':
        return CAR;
      default:
        return CAR;
    }
  }

  /// Traccar Position attributes key ko matching icon Asset path se return karna
  static String getIconByTraccarAttribute(String attributeKey) {
    switch (attributeKey.toLowerCase()) {
      case 'battery':
      case 'batterylevel':
        return BATTERY;
      case 'power':
      case 'charge':
        return ELECTRICBATERY;
      case 'ignition':
      case 'engine':
        return POWER;
      case 'sat':
      case 'satellites':
      case 'gps':
        return SATTELITE;
      case 'rssi':
      case 'gsm':
      case 'signal':
        return ANTENNA;
      case 'speed':
      case 'speedometer':
        return SPEEDOMETER;
      default:
        return SENSOR;
    }
  }
}
