/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String DIGITAL_DISPLAY = 'Digital-Display';
  static const String MONTSERRAT_REGULAR = 'Montserrat-Regular';
  static const String NEUCHA_REGULAR = 'Neucha-Regular';
  static const String PHILOSOPHER_REGULAR = 'Philosopher-Regular';
  static const String SACRAMENTO_REGULAR = 'Sacramento-Regular';
  static const String UBUNTUMONO_REGULAR = 'UbuntuMono-Regular';
  static const String YESEVAONE_REGULAR = 'YesevaOne-Regular';

  // ==========================================
  // TRACCAR API BACKEND FONT INTEGRATION
  // ==========================================

  /// Traccar position/telemetry data (Speed, Odometer, Coordinates) ke liye font select karne ka helper
  static String getTelemetryFont({bool isDigitalStyle = false}) {
    return isDigitalStyle ? DIGITAL_DISPLAY : UBUNTUMONO_REGULAR;
  }

  /// Traccar `/api/session` ya `/api/users` response ke attributes se user font preference parse karna
  static String getFontFromTraccarUser(Map<String, dynamic> userJson) {
    if (userJson.containsKey('attributes') && userJson['attributes'] is Map) {
      final attrs = userJson['attributes'] as Map<String, dynamic>;
      final fontName = attrs['fontFamily'] ?? attrs['font'] ?? attrs['appFont'];
      if (fontName != null && fontName.toString().isNotEmpty) {
        return parseFontName(fontName.toString());
      }
    }
    return MONTSERRAT_REGULAR; // Default fallback font
  }

  /// Traccar `/api/server` response se server-wide custom font setting load karna
  static String getFontFromTraccarServer(Map<String, dynamic> serverJson) {
    if (serverJson.containsKey('attributes') && serverJson['attributes'] is Map) {
      final attrs = serverJson['attributes'] as Map<String, dynamic>;
      final fontName = attrs['defaultFont'] ?? attrs['fontFamily'];
      if (fontName != null && fontName.toString().isNotEmpty) {
        return parseFontName(fontName.toString());
      }
    }
    return MONTSERRAT_REGULAR;
  }

  /// Custom Font string ko `FontRes` constants se safe mapping
  static String parseFontName(String fontName) {
    switch (fontName.toLowerCase()) {
      case 'digital':
      case 'digital-display':
      case 'speedometer':
        return DIGITAL_DISPLAY;
      case 'neucha':
        return NEUCHA_REGULAR;
      case 'philosopher':
        return PHILOSOPHER_REGULAR;
      case 'sacramento':
        return SACRAMENTO_REGULAR;
      case 'mono':
      case 'ubuntumono':
        return UBUNTUMONO_REGULAR;
      case 'yeseva':
      case 'yesevaone':
        return YESEVAONE_REGULAR;
      case 'montserrat':
      default:
        return MONTSERRAT_REGULAR;
    }
  }
}
