/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PLUGIN_NAME = 'speedotrack';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String KM_SUMMARY = 'images/km_summary.png';
  static const String PLAYBACK = 'images/playback.png';

  // ==========================================
  // TRACCAR API BACKEND IMAGE INTEGRATION
  // ==========================================

  /// Traccar Report type (`/api/reports/summary`, `/api/reports/route`, etc.) ke according matching asset path
  static String getImageForReportType(String reportType) {
    switch (reportType.toLowerCase()) {
      case 'summary':
      case 'kmsummary':
      case 'distance':
      case 'daily':
        return KM_SUMMARY;
      case 'route':
      case 'trips':
      case 'stops':
      case 'playback':
      case 'replay':
      case 'history':
        return PLAYBACK;
      default:
        return PLAYBACK;
    }
  }

  /// Traccar Server hosted custom file/branding image URL (`/api/server/file/{path}`)
  static String getTraccarServerFileUrl(String baseUrl, String path) {
    final cleanBase = baseUrl.endsWith('/') ? baseUrl.substring(0, baseUrl.length - 1) : baseUrl;
    final cleanPath = path.startsWith('/') ? path.substring(1) : path;
    return '$cleanBase/api/server/file/$cleanPath';
  }

  /// Traccar Device custom photo/image API endpoint (`/api/devices/{id}/image`)
  static String getTraccarDeviceImageUrl(String baseUrl, int deviceId) {
    final cleanBase = baseUrl.endsWith('/') ? baseUrl.substring(0, baseUrl.length - 1) : baseUrl;
    return '$cleanBase/api/devices/$deviceId/image';
  }
}
