// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'User.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) {
  // Extract nested Traccar attributes map if available
  final attributes = json['attributes'] is Map<String, dynamic>
      ? json['attributes'] as Map<String, dynamic>
      : null;

  return UserModel(
    username: (json['username'] ?? json['name'] ?? json['email']) as String?,
    email: json['email'] as String?,
    manager_id: (json['manager_id'] ?? json['userLimit']?.toString()) as String?,
    cpanel_privileges: json['cpanel_privileges'],
    privileges: json['privileges'] != null
        ? json['privileges'] as String?
        : (json['administrator'] == true ? 'admin' : 'user'),
    privileges_imei: json['privileges_imei'] as String?,
    privileges_marker: json['privileges_marker'] as String?,
    privileges_route: json['privileges_route'] as String?,
    privileges_zone: json['privileges_zone'] as String?,
    privileges_dashboard: json['privileges_dashboard'] as bool? ?? true,
    privileges_history: json['privileges_history'] as bool? ?? true,
    privileges_reports: json['privileges_reports'] as bool? ??
        (json['readonly'] != null ? !(json['readonly'] as bool) : true),
    privileges_tasks: json['privileges_tasks'] as bool? ?? true,
    privileges_rilogbook: json['privileges_rilogbook'] as bool? ?? true,
    privileges_dtc: json['privileges_dtc'] as bool? ?? true,
    privileges_maintenance: json['privileges_maintenance'] as bool? ?? true,
    privileges_expenses: json['privileges_expenses'] as bool? ?? true,
    privileges_object_control: json['privileges_object_control'] as bool? ??
        (json['readonly'] != null ? !(json['readonly'] as bool) : true),
    privileges_image_gallery: json['privileges_image_gallery'] as bool? ?? true,
    privileges_chat: json['privileges_chat'] as bool? ?? true,
    privileges_subaccounts: json['privileges_subaccounts'] as bool? ??
        (json['administrator'] == true),
    billing: json['billing'] as bool? ??
        (json['readonly'] != null ? !(json['readonly'] as bool) : null),
    obj_add: json['obj_add'] as String? ??
        (json['readonly'] == true ? 'false' : 'true'),
    obj_limit: (json['obj_limit'] ?? json['deviceLimit']?.toString()) as String?,
    obj_limit_num: (json['obj_limit_num'] ?? json['deviceLimit']?.toString()) as String?,
    obj_days: json['obj_days'] as String?,
    obj_days_dt: json['obj_days_dt'] as String?,
    obj_edit: json['obj_edit'] as String? ??
        (json['readonly'] == true ? 'false' : 'true'),
    obj_delete: json['obj_delete'] as String? ??
        (json['readonly'] == true ? 'false' : 'true'),
    obj_history_clear: json['obj_history_clear'] as String?,
    chat_notify: json['chat_notify'] as String?,
    map_sp: json['map_sp'] as String?,
    map_is: json['map_is'] as String?,
    map_rc: json['map_rc'] as String?,
    map_rhc: json['map_rhc'] as String?,
    map_ocp: json['map_ocp'] as String?,
    groups_collapsed: json['groups_collapsed'] as Map<String, dynamic>?,
    od: json['od'] as String?,
    ohc: json['ohc'] as Map<String, dynamic>?,
    datalist: json['datalist'] as String?,
    datalist_items: json['datalist_items'] as String?,
    push_notify_desktop: json['push_notify_desktop'] as String?,
    push_notify_mobile: json['push_notify_mobile'] as String?,
    push_notify_mobile_interval: json['push_notify_mobile_interval'],
    sms_gateway: json['sms_gateway'] as String?,
    sms_gateway_type: json['sms_gateway_type'] as String?,
    sms_gateway_url: json['sms_gateway_url'] as String?,
    sms_gateway_identifier: json['sms_gateway_identifier'] as String?,
    sms_gateway_total_in_queue: json['sms_gateway_total_in_queue'] as int?,
    startup_tab: json['startup_tab'] as String?,
    language: (json['language'] ?? attributes?['language']) as String?,
    unit_distance: (json['unit_distance'] ?? attributes?['distanceUnit']) as String?,
    unit_capacity: (json['unit_capacity'] ?? attributes?['volumeUnit']) as String?,
    unit_temperature: (json['unit_temperature'] ?? attributes?['temperatureUnit']) as String?,
    currency: (json['currency'] ?? attributes?['currency']) as String?,
    timezone: (json['timezone'] ?? attributes?['timezone']) as String?,
    dst: json['dst'] as String?,
    dst_start: json['dst_start'] as String?,
    dst_end: json['dst_end'] as String?,
    info: (json['info'] as Map<String, dynamic>?) ?? attributes,
    usage_email_daily: json['usage_email_daily'] as String?,
    usage_sms_daily: json['usage_sms_daily'] as String?,
    usage_api_daily: json['usage_api_daily'] as String?,
    usage_email_daily_cnt: json['usage_email_daily_cnt'] as String?,
    usage_sms_daily_cnt: json['usage_sms_daily_cnt'] as String?,
    usage_api_daily_cnt: json['usage_api_daily_cnt'] as String?,
    cards: json['cards'] as String?,
  );
}

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'username': instance.username,
      'email': instance.email,
      'manager_id': instance.manager_id,
      'cpanel_privileges': instance.cpanel_privileges,
      'privileges': instance.privileges,
      'privileges_imei': instance.privileges_imei,
      'privileges_marker': instance.privileges_marker,
      'privileges_route': instance.privileges_route,
      'privileges_zone': instance.privileges_zone,
      'privileges_dashboard': instance.privileges_dashboard,
      'privileges_history': instance.privileges_history,
      'privileges_reports': instance.privileges_reports,
      'privileges_tasks': instance.privileges_tasks,
      'privileges_rilogbook': instance.privileges_rilogbook,
      'privileges_dtc': instance.privileges_dtc,
      'privileges_maintenance': instance.privileges_maintenance,
      'privileges_expenses': instance.privileges_expenses,
      'privileges_object_control': instance.privileges_object_control,
      'privileges_image_gallery': instance.privileges_image_gallery,
      'privileges_chat': instance.privileges_chat,
      'privileges_subaccounts': instance.privileges_subaccounts,
      'billing': instance.billing,
      'obj_add': instance.obj_add,
      'obj_limit': instance.obj_limit,
      'obj_limit_num': instance.obj_limit_num,
      'obj_days': instance.obj_days,
      'obj_days_dt': instance.obj_days_dt,
      'obj_edit': instance.obj_edit,
      'obj_delete': instance.obj_delete,
      'obj_history_clear': instance.obj_history_clear,
      'chat_notify': instance.chat_notify,
      'map_sp': instance.map_sp,
      'map_is': instance.map_is,
      'map_rc': instance.map_rc,
      'map_rhc': instance.map_rhc,
      'map_ocp': instance.map_ocp,
      'groups_collapsed': instance.groups_collapsed,
      'od': instance.od,
      'ohc': instance.ohc,
      'datalist': instance.datalist,
      'datalist_items': instance.datalist_items,
      'push_notify_desktop': instance.push_notify_desktop,
      'push_notify_mobile': instance.push_notify_mobile,
      'push_notify_mobile_interval': instance.push_notify_mobile_interval,
      'sms_gateway': instance.sms_gateway,
      'sms_gateway_type': instance.sms_gateway_type,
      'sms_gateway_url': instance.sms_gateway_url,
      'sms_gateway_identifier': instance.sms_gateway_identifier,
      'sms_gateway_total_in_queue': instance.sms_gateway_total_in_queue,
      'startup_tab': instance.startup_tab,
      'language': instance.language,
      'unit_distance': instance.unit_distance,
      'unit_capacity': instance.unit_capacity,
      'unit_temperature': instance.unit_temperature,
      'currency': instance.currency,
      'timezone': instance.timezone,
      'dst': instance.dst,
      'dst_start': instance.dst_start,
      'dst_end': instance.dst_end,
      'info': instance.info,
      'usage_email_daily': instance.usage_email_daily,
      'usage_sms_daily': instance.usage_sms_daily,
      'usage_api_daily': instance.usage_api_daily,
      'usage_email_daily_cnt': instance.usage_email_daily_cnt,
      'usage_sms_daily_cnt': instance.usage_sms_daily_cnt,
      'usage_api_daily_cnt': instance.usage_api_daily_cnt,
      'cards': instance.cards,

      // Traccar REST API direct payload keys (POST/PUT /api/users, /api/session)
      'name': instance.username,
      'administrator': instance.privileges == 'admin' || (instance.privileges_subaccounts ?? false),
      'readonly': instance.billing == false,
      'deviceLimit': int.tryParse(instance.obj_limit ?? '-1') ?? -1,
      'attributes': {
        'language': instance.language ?? 'en',
        'distanceUnit': instance.unit_distance ?? 'km',
        'volumeUnit': instance.unit_capacity ?? 'liter',
        'temperatureUnit': instance.unit_temperature ?? 'celsius',
        'timezone': instance.timezone ?? 'UTC',
        'currency': instance.currency ?? 'PKR',
        ...?instance.info,
      },
    };
