// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:convert';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:http/http.dart' as http;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NRl4zgvBEqwaJg_UGstpwrMRUiV15OI',
    appId: '1:883633293769:android:28b27b69f84849d9448018',
    messagingSenderId: '883633293769',
    projectId: 'infinity-b44d7',
    databaseURL: 'https://infinity-b44d7-default-rtdb.firebaseio.com',
    storageBucket: 'infinity-b44d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4q9z2X0avCy2IDJUzy4NHCqzsXwaT6s',
    appId: '1:883633293769:ios:4e5afafd46812203448018',
    messagingSenderId: '883633293769',
    projectId: 'infinity-b44d7',
    databaseURL: 'https://infinity-b44d7-default-rtdb.firebaseio.com',
    storageBucket: 'infinity-b44d7.firebasestorage.app',
    iosClientId: '847296525014-8d6vg8a08lfk1mp8j6mbgv96gq3n7cob.apps.googleusercontent.com',
    iosBundleId: 'com.infinity.track',
  );
}

// ==========================================
// TRACCAR API & FIREBASE NOTIFICATION BACKEND
// ==========================================

class TraccarFirebaseSync {
  /// Firebase FCM Push Token ko Traccar API `/api/users/{id}` par user attributes me sync karna
  static Future<bool> syncFcmTokenToTraccarUser({
    required String baseUrl,
    required int userId,
    required String fcmToken,
    String? sessionCookie,
    String? basicAuthHeader,
  }) async {
    try {
      final cleanUrl = baseUrl.endsWith('/')
          ? baseUrl.substring(0, baseUrl.length - 1)
          : baseUrl;

      final getUserUrl = Uri.parse('$cleanUrl/api/users/$userId');

      // Request Headers setup
      Map<String, String> headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      };

      if (sessionCookie != null && sessionCookie.isNotEmpty) {
        headers['Cookie'] = sessionCookie;
      } else if (basicAuthHeader != null && basicAuthHeader.isNotEmpty) {
        headers['Authorization'] = basicAuthHeader;
      }

      // 1. Current user details fetch karein
      final getResponse = await http.get(getUserUrl, headers: headers);

      if (getResponse.statusCode == 200) {
        final Map<String, dynamic> userData = jsonDecode(getResponse.body);
        final Map<String, dynamic> attributes = userData['attributes'] != null
            ? Map<String, dynamic>.from(userData['attributes'])
            : {};

        // 2. Existing notification tokens handle karein (comma separated or single)
        String existingTokens = attributes['notificationTokens']?.toString() ?? '';
        if (!existingTokens.contains(fcmToken)) {
          if (existingTokens.isNotEmpty) {
            attributes['notificationTokens'] = '$existingTokens,$fcmToken';
          } else {
            attributes['notificationTokens'] = fcmToken;
          }
        }

        userData['attributes'] = attributes;

        // 3. Updated user object PUT request ke zariye Traccar API par save karein
        final putResponse = await http.put(
          getUserUrl,
          headers: headers,
          body: jsonEncode(userData),
        );

        return putResponse.statusCode == 200;
      }
    } catch (e) {
      // Error logging for backend sync
    }
    return false;
  }
}
